version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
