version: "3.9"
services:
  api:
    container_name: node-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
